### ISSUE TITLE
Video not playing correctly.

### ISSUE THREAD

**Issue by ericarojo692** [learn-co-curriculum/phase-1-lecture-videos-intro-to-dom#1] opened 2021-08-16 02:23 UTC
Thanks for raising this issue! Future learners thank you for your diligence. In
order to help the curriculum team address the problem, please use this template
to submit your feedback. We'll work on addressing the issue as soon as we can.

Please fill out as much of the information below as you can (it's ok if you
don't fill out every section). The more context we have, the easier it will be
to fix your issue!

_**Note**: you should only raise issues related to the contents of this lesson.
If you have questions about your code or need help troubleshooting, reach out to
an instructor/your peers._

---

## Link to Canvas

Add a link to the assignment in Canvas here.

## Describe the bug

Write a clear and concise description of what the bug is. Include the file and
line number(s) if possible.

## What is the expected behavior?

Write a clear and concise description of what you expected to happen.

## Screenshots

If applicable, attach screenshots to help explain your problem.

## What OS are you using?

- [ ] OS X
- [ ] WSL
- [ ] Linux

**Comment by ihollander** [comment] 2021-08-19 13:29
Hi @ericarojo692 - thanks for flagging this issue. I'm not able to recreate the problem you're experiencing - the videos seem to be working as expected for this lesson and the others you mentioned. Can you give more details about what's not working, like a screenshot and a link to the Canvas page where the issue is occurring?

**Comment by ihollander** [comment] 2021-08-25 20:51
Hi @ericarojo692 - I'm closing this issue since I wasn't able to recreate it. Please feel free to re-open this issue if it persists!

**Closed as completed by ihollander** 2021-08-25 20:51 UTC
Labels: bug
